import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning  
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {/* <div>
          <Link href={"/"}></Link>
          <Link href={"/about"}>About </Link>
          <Link href={"/contact"}>Contact </Link>
          <Link href={"/users"}>Users </Link>
          <Link href={"/jokes"}>jokes </Link>
          <Link href={"/alquran"}>al-Quran </Link>
        </div> */}
        {children}
        <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
